### ISSUE TITLE
Properties tab broken?

### ISSUE THREAD

**Issue by misaka00251** [LITDARK/Dark-Transparency-Theme#2]
![image](https://user-images.githubusercontent.com/3908746/146862883-60affc82-d7e2-4934-bedc-0a82e9eacd28.png)

Full error below:

```
An exception was encountered while constructing the content of this frame.  This information is also logged in "C:\Users\misaka00251\AppData\Roaming\Microsoft\VisualStudio\17.0_852bf740\ActivityLog.xml".

Exception details:
System.ArgumentException: Control does not support transparent background colors.
   at System.Windows.Forms.Control.set_BackColor(Color value)
   at Microsoft.VisualStudio.PropertyBrowser.PropertyBrowser.ApplyThemeColors()
   at Microsoft.VisualStudio.PropertyBrowser.PropertyBrowser.CreateUI()
   at Microsoft.VisualStudio.PropertyBrowser.PropertyBrowser..ctor(IServiceProvider serviceProvider)
   at Microsoft.VisualStudio.PropertyBrowser.PropertyBrowserService.get_PropertyBrowser()
   at Microsoft.VisualStudio.PropertyBrowser.PropertyBrowserService.get_Window()
   at Microsoft.VisualStudio.Shell.WindowPane.Microsoft.VisualStudio.Shell.Interop.IVsUIElementPane.CreateUIElementPane(Object& uiElement)
   at Microsoft.VisualStudio.Platform.WindowManagement.UIElementDocumentObject.Init(Boolean initSize)
   at Microsoft.VisualStudio.Platform.WindowManagement.DocumentObjectSite.InitializeDocumentObject(Object punkView)
   at Microsoft.VisualStudio.Platform.WindowManagement.PropertyBrowserSwitcher.OnQuerySwitchPane(FrameMoniker frameMoniker)
   at Microsoft.VisualStudio.Platform.WindowManagement.ContextSwitchFrame.OnElementValueChanged(UInt32 elementid, Object varValueOld, Object varValueNew)
   at Microsoft.VisualStudio.Platform.WindowManagement.ContextSwitchFrame.OnToolWindowCreated()
   at Microsoft.VisualStudio.Platform.WindowManagement.PropertyBrowserSwitcher.OnToolWindowCreated()
   at Microsoft.VisualStudio.Shell.Package.HandleToolWindowCreation(ToolWindowCreationResult result, Int32 id, Guid persistenceGuid, IVsWindowFrame frame)
   at Microsoft.VisualStudio.Shell.Package.<>c__DisplayClass84_0.<CreateToolWindow>g__CreateToolWindowWorker|1()
   at Microsoft.VisualStudio.Shell.Package.CreateToolWindow(Type toolWindowType, Int32 id, UInt32 flags, Object context, Guid persistenceGuid)
   at Microsoft.VisualStudio.Shell.Package.<>c__DisplayClass94_1.<<FindToolWindow>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Shell.Package.<>c__DisplayClass94_0.<<FindToolWindow>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Shell.ToolWindowCollection.ToolWindowListener.<>c__DisplayClass1_0.<<-ctor>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.AwaitExtensions.ExecuteContinuationSynchronouslyAwaiter`1.GetResult()
   at Microsoft.VisualStudio.Threading.AsyncLazy`1.<>c__DisplayClass13_0.<<GetValueAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.AsyncLazy`1.GetValue(CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Shell.Package.FindToolWindow(Type toolWindowType, Int32 id, Boolean create, ProvideToolWindowAttribute tool)
   at Microsoft.VisualStudio.Shell.Package.CreateToolWindow(Guid& toolWindowType, Int32 id)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.ConstructContent()
```

**Comment by LITDARK** [comment]
In order to change the background of some tool windows like Git Changes and Notification, I changed the color in
`Environment → ToolWindowBackground`
But seems like it will affect the Properties window too, and this window don't accept background as transparency.

Fixed in [v1.0.3](https://github.com/LITDARK/Dark-Transparency-Theme/releases/tag/v1.0.3), but some tool window's background will not be transparency any more.

Anyway, thanks for testing this theme ;)
